"""
GitHub Issues integration — rich issue body builder.
"""

from __future__ import annotations

import os
from typing import Optional
from github import Github, GithubException
from core.models import ActionItem


def _get_client() -> Github:
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        raise ValueError("GITHUB_TOKEN not set in environment")
    return Github(token)


def _get_repo(client: Github):
    repo_name = os.getenv("GITHUB_REPO")
    if not repo_name:
        raise ValueError("GITHUB_REPO not set (format: username/repo-name)")
    return client.get_repo(repo_name)


# ─────────────────────────────────────────────
# Dedup check
# ─────────────────────────────────────────────

def issue_already_exists(title: str) -> Optional[str]:
    """
    Search GitHub for an open issue with the same title.
    Returns the issue URL if found, None otherwise.
    """
    try:
        client = _get_client()
        repo   = _get_repo(client)
        query  = f'repo:{os.getenv("GITHUB_REPO")} is:issue is:open "{title}" in:title'
        issues = client.search_issues(query=query)
        for issue in issues:
            if issue.title.strip().lower() == title.strip().lower():
                return issue.html_url
        return None
    except Exception:
        return None


def get_repo_collaborators() -> list[dict]:
    """
    Fetch all collaborators from the configured GitHub repo.
    Returns list of {"login": "username", "name": "Display Name or login"}.
    Returns [] if GitHub is not configured or on any error.
    """
    try:
        client = _get_client()
        repo   = _get_repo(client)
        result = []
        for collab in repo.get_collaborators():
            result.append({
                "login": collab.login,
                "name":  collab.name or collab.login,
            })
        return result
    except Exception:
        return []


# ─────────────────────────────────────────────
# Issue body builder — rich & descriptive
# ─────────────────────────────────────────────

def _build_issue_body(item: ActionItem, meeting_date: str) -> str:
    owner_name  = item.resolved_owner.name  if item.resolved_owner else item.raw_owner or "Unassigned"
    owner_email = item.resolved_owner.email if item.resolved_owner else "—"
    github_user = item.resolved_owner.github_username if item.resolved_owner else None
    due_date    = str(item.resolved_date) if item.resolved_date else item.raw_due_date or "Not specified"
    priority    = (item.priority.value if hasattr(item.priority, "value") else str(item.priority)).capitalize()
    conf_pct    = int(item.confidence * 100)

    priority_emoji = {"High": "🔴", "Medium": "🟡", "Low": "🟢"}.get(priority, "⚪")
    conf_emoji     = "✅" if conf_pct >= 85 else "⚠️" if conf_pct >= 60 else "❌"

    assignee_line = f"@{github_user}" if github_user else f"{owner_name} ({owner_email})"

    # Description section — from LLM extraction, grounded in transcript
    description_section = ""
    if item.description and item.description.strip():
        description_section = f"""
## 📝 What needs to be done

{item.description.strip()}

"""

    # Evidence from transcript
    evidence_section = ""
    if item.evidence_quote:
        ts = f"\n> *Timestamp: {item.evidence_timestamp}*" if item.evidence_timestamp else ""
        evidence_section = f"""
## 🗣️ Source — from meeting transcript

> "{item.evidence_quote}"{ts}

"""

    # Raw date context if resolved date differs
    date_note = ""
    if item.raw_due_date and str(item.resolved_date) != item.raw_due_date:
        date_note = f" *(originally mentioned as: \"{item.raw_due_date}\")*"

    return f"""## Overview

{description_section}

## 📋 Task Details

| Field | Value |
|---|---|
| **Assigned to** | {assignee_line} |
| **Due date** | {due_date}{date_note} |
| **Priority** | {priority_emoji} {priority} |
| **Confidence** | {conf_emoji} {conf_pct}% extraction confidence |
| **Meeting date** | {meeting_date} |
{evidence_section}
---

### ✅ Acceptance Criteria

- [ ] Task completed and verified by assignee
- [ ] Outcome communicated back to the team
- [ ] Any blockers escalated promptly

---
*🤖 Auto-generated by [MeetingMind](https://github.com/meetingmind) from the meeting on {meeting_date}.*
*Item ID: `{item.id}` · Dedup key: `{item.dedup_key or "N/A"}`*
"""


# ─────────────────────────────────────────────
# Create single issue
# ─────────────────────────────────────────────

def create_github_issue(item: ActionItem, meeting_date: str) -> dict:
    """
    Create a GitHub issue for one approved action item.
    Returns a result dict with issue_url and metadata.
    """
    client = _get_client()
    repo   = _get_repo(client)

    assignees = []
    if item.resolved_owner and item.resolved_owner.github_username:
        username = item.resolved_owner.github_username
        assignees.append(username)

    priority_str = item.priority.value if hasattr(item.priority, "value") else str(item.priority)
    labels = ["meeting-action-item", f"priority:{priority_str}"]
    _ensure_labels(repo, labels)

    body  = _build_issue_body(item, meeting_date)
    issue = repo.create_issue(
        title     = item.title,
        body      = body,
        assignees = assignees,
        labels    = labels,
    )

    return {
        "item_id":      item.id,
        "issue_number": issue.number,
        "issue_url":    issue.html_url,
        "title":        item.title,
    }


def _ensure_labels(repo, label_names: list[str]) -> None:
    """Create any labels that don't exist yet in the repo."""
    existing = {label.name for label in repo.get_labels()}
    color_map = {
        "meeting-action-item": "0075ca",
        "priority:high":       "d93f0b",
        "priority:medium":     "e4e669",
        "priority:low":        "0e8a16",
    }
    for name in label_names:
        if name not in existing:
            try:
                repo.create_label(name=name, color=color_map.get(name, "cccccc"))
            except GithubException:
                pass


# ─────────────────────────────────────────────
# Batch async create
# ─────────────────────────────────────────────

async def create_issues_async(items: list[ActionItem], meeting_date: str) -> list[dict]:
    import asyncio
    async def _create_one(item: ActionItem) -> Optional[dict]:
        try:
            loop   = asyncio.get_event_loop()
            result = await loop.run_in_executor(None, create_github_issue, item, meeting_date)
            return result
        except Exception as e:
            return {"item_id": item.id, "error": str(e), "issue_url": None}

    tasks   = [_create_one(item) for item in items]
    results = await asyncio.gather(*tasks)
    return [r for r in results if r]
